export type DevIncidentCase = {
  name: string;
  category: string;
  racePhase: string;
  impact: string;
  evidenceReadiness: string;
  event: string;
  lapOrTime: string;
  involvedDriversText: string;
  description: string;
  evidenceUrl?: string;
};

export const devIncidentCases: DevIncidentCase[] = [
  {
    name: "collision-basic",
    category: "collision",
    racePhase: "green_flag",
    impact: "position_loss",
    evidenceReadiness: "strong_clip",
    event: "Round 1 - Maple Valley",
    lapOrTime: "Lap 4, Turn 3",
    involvedDriversText: "DriverAlpha, DriverBravo",
    description: "DriverBravo sends DriverAlpha wide after late contact at corner entry. Alpha loses two positions.",
    evidenceUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    name: "collision-no-damage",
    category: "collision",
    racePhase: "green_flag",
    impact: "no_damage",
    evidenceReadiness: "short_clip",
    event: "Round 1 - Maple Valley",
    lapOrTime: "Lap 7, final corner",
    involvedDriversText: "DriverCharlie, DriverDelta",
    description: "Light door contact with no visible damage or position change. Submitted to check if warning applies.",
  },
  {
    name: "collision-severe",
    category: "collision",
    racePhase: "green_flag",
    impact: "severe_obstacle",
    evidenceReadiness: "strong_clip",
    event: "Round 2 - Road America",
    lapOrTime: "Lap 2, Turn 5",
    involvedDriversText: "DriverEcho, DriverFoxtrot, DriverGolf",
    description: "Multi-car crash leaves DriverEcho limping on racing line with severe damage.",
    evidenceUrl: "https://youtu.be/dQw4w9WgXcQ",
  },
  {
    name: "track-limits-repeat",
    category: "track_limits",
    racePhase: "green_flag",
    impact: "repeated_behavior",
    evidenceReadiness: "stream_replay",
    event: "Round 2 - Road America",
    lapOrTime: "Laps 6-10, Turn 1 exit",
    involvedDriversText: "DriverHotel",
    description: "DriverHotel repeatedly extends track limits on corner exit and appears to gain time.",
  },
  {
    name: "track-limits-final",
    category: "track_limits",
    racePhase: "final_laps",
    impact: "position_loss",
    evidenceReadiness: "strong_clip",
    event: "Round 3 - Silverstone",
    lapOrTime: "Final lap, Club corner",
    involvedDriversText: "DriverIndia, DriverJuliet",
    description: "DriverIndia runs wide beyond limits on final lap and keeps position over DriverJuliet.",
  },
  {
    name: "blue-flag-brake",
    category: "blue_flag",
    racePhase: "being_lapped",
    impact: "minor_damage",
    evidenceReadiness: "strong_clip",
    event: "Round 3 - Silverstone",
    lapOrTime: "Lap 15, Hangar Straight",
    involvedDriversText: "DriverKilo, DriverLima",
    description: "Backmarker brakes on straight while being passed by lead-lap car, causing contact.",
  },
  {
    name: "blue-flag-block",
    category: "blue_flag",
    racePhase: "final_laps",
    impact: "position_loss",
    evidenceReadiness: "short_clip",
    event: "Round 4 - Spa",
    lapOrTime: "Lap 18, Kemmel Straight",
    involvedDriversText: "DriverMike, DriverNovember",
    description: "Backmarker does not safely yield to lead-lap battle and disrupts pass attempt.",
  },
  {
    name: "yellow-pass",
    category: "yellow_flag",
    racePhase: "during_caution",
    impact: "illegal_pass",
    evidenceReadiness: "strong_clip",
    event: "Round 4 - Spa",
    lapOrTime: "Yellow flag lap, after Bus Stop",
    involvedDriversText: "DriverOscar, DriverPapa",
    description: "DriverOscar passes DriverPapa after full-course yellow was announced.",
  },
  {
    name: "yellow-pause",
    category: "yellow_flag",
    racePhase: "caution_lineup",
    impact: "procedure_issue",
    evidenceReadiness: "stream_replay",
    event: "Round 5 - Watkins Glen",
    lapOrTime: "Yellow flag lap 2",
    involvedDriversText: "DriverQuebec",
    description: "DriverQuebec appears to pause while in caution line, causing gap and position confusion.",
  },
  {
    name: "yellow-severe-car",
    category: "yellow_flag",
    racePhase: "caution_call",
    impact: "severe_obstacle",
    evidenceReadiness: "strong_clip",
    event: "Round 5 - Watkins Glen",
    lapOrTime: "Lap 9, Esses",
    involvedDriversText: "DriverRomeo",
    description: "Severely damaged car is slow on track and becomes an obstacle before reaching pit lane.",
  },
  {
    name: "reentry-unsafe",
    category: "reentry",
    racePhase: "green_flag",
    impact: "significant_damage",
    evidenceReadiness: "strong_clip",
    event: "Round 6 - Laguna Seca",
    lapOrTime: "Lap 3, Corkscrew exit",
    involvedDriversText: "DriverSierra, DriverTango",
    description: "DriverSierra rejoins from off-track directly into DriverTango and causes significant damage.",
  },
  {
    name: "reentry-turnaround",
    category: "reentry",
    racePhase: "qualifying",
    impact: "position_loss",
    evidenceReadiness: "short_clip",
    event: "Round 6 - Laguna Seca",
    lapOrTime: "Qualifying lap 2",
    involvedDriversText: "DriverUniform, DriverVictor",
    description: "DriverUniform turns around on track during qualifying and blocks DriverVictor's flying lap.",
  },
  {
    name: "pit-exit-line",
    category: "pit_exit",
    racePhase: "green_flag",
    impact: "no_damage",
    evidenceReadiness: "strong_clip",
    event: "Round 7 - Suzuka",
    lapOrTime: "Lap 11, pit exit",
    involvedDriversText: "DriverWhiskey",
    description: "DriverWhiskey crosses pit exit line while merging back onto track.",
  },
  {
    name: "pit-exit-contact",
    category: "pit_exit",
    racePhase: "caution_pits",
    impact: "minor_damage",
    evidenceReadiness: "stream_replay",
    event: "Round 7 - Suzuka",
    lapOrTime: "Caution lap, pit exit",
    involvedDriversText: "DriverXray, DriverYankee",
    description: "DriverXray exits pits under caution and merges into DriverYankee, causing minor damage.",
  },
  {
    name: "build-wrong-handicap",
    category: "build_livery",
    racePhase: "qualifying",
    impact: "eligibility_issue",
    evidenceReadiness: "strong_clip",
    event: "Round 8 - Le Mans",
    lapOrTime: "Pre-race qualifying inspection",
    involvedDriversText: "DriverZulu",
    description: "DriverZulu appears to be using the wrong group bucket power handicap.",
  },
  {
    name: "livery-missing",
    category: "build_livery",
    racePhase: "practice",
    impact: "eligibility_issue",
    evidenceReadiness: "short_clip",
    event: "Round 8 - Le Mans",
    lapOrTime: "Practice lobby",
    involvedDriversText: "DriverAtlas",
    description: "DriverAtlas entered the lobby without the required livery.",
  },
  {
    name: "voice-arguing",
    category: "voice_chat",
    racePhase: "race_voice",
    impact: "conduct_only",
    evidenceReadiness: "stream_replay",
    event: "Round 9 - Nürburgring GP",
    lapOrTime: "Mid-race voice chat",
    involvedDriversText: "DriverBishop, DriverComet",
    description: "Drivers argue in voice chat during race session after contact, disrupting the lobby.",
  },
  {
    name: "voice-abuse",
    category: "voice_chat",
    racePhase: "post_race",
    impact: "conduct_only",
    evidenceReadiness: "strong_clip",
    event: "Round 9 - Nürburgring GP",
    lapOrTime: "Post-race lobby",
    involvedDriversText: "DriverDagger",
    description: "DriverDagger verbally abuses another participant after the race.",
  },
  {
    name: "pace-lap-formation",
    category: "race_procedure",
    racePhase: "formation",
    impact: "procedure_issue",
    evidenceReadiness: "strong_clip",
    event: "Round 10 - Mugello",
    lapOrTime: "Pace lap, final sector",
    involvedDriversText: "DriverGale, DriverHarbor",
    description: "DriverGale repeatedly fails to hold formation, closes under 2 car lengths, and disrupts the double-file start.",
  },
  {
    name: "qualifying-reverse",
    category: "race_procedure",
    racePhase: "qualifying_reverse",
    impact: "procedure_issue",
    evidenceReadiness: "strong_clip",
    event: "Round 10 - Mugello",
    lapOrTime: "Qualifying start",
    involvedDriversText: "DriverIvory",
    description: "DriverIvory reverses at the start of qualifying, matching the explicit rule issue from the procedures.",
  },
  {
    name: "cheating-exploit",
    category: "competitive_integrity",
    racePhase: "green_flag",
    impact: "integrity_issue",
    evidenceReadiness: "stream_replay",
    event: "Round 10 - Mugello",
    lapOrTime: "Laps 8-12",
    involvedDriversText: "DriverJade",
    description: "DriverJade appears to use an exploit or cheat behavior that gives abnormal straight-line speed.",
  },
  {
    name: "needs-upload",
    category: "collision",
    racePhase: "green_flag",
    impact: "position_loss",
    evidenceReadiness: "needs_upload",
    event: "Round 10 - Mugello",
    lapOrTime: "Lap 1, Turn 1",
    involvedDriversText: "DriverEmber, DriverFrost",
    description: "Lap-one contact caused position loss. Reporter has clip but needs to upload and add link later.",
  },
  {
    name: "no-clip-edge",
    category: "other",
    racePhase: "post_race",
    impact: "no_damage",
    evidenceReadiness: "no_clip",
    event: "Round 10 - Mugello",
    lapOrTime: "Unknown",
    involvedDriversText: "DriverGhost",
    description: "Edge case: report submitted with no clip yet. Useful for testing need-more-info handling.",
  },
];
